"""Writes docs/MODEL_VALIDATION.md from the two validation reports, so the document cannot drift from the numbers.

    python3 -m research.product_models.report
"""
from __future__ import annotations

from pathlib import Path

from . import live, team_goalie

DOC = Path(__file__).resolve().parent.parent.parent / "docs" / "MODEL_VALIDATION.md"


def render() -> str:
    sk = live.load_validation()
    sv = live.market_verdicts(sk)
    gv = team_goalie.load_validation()
    sav = team_goalie.saves_verdicts(gv)
    wp = gv["win_probability"]
    out = ["# Model validation and the live-model policy", "",
           "Generated by `python3 -m research.product_models.report` from `docs/validation/*.json`. Reports are produced by",
           "`python3 -m research.product_models.validate` (skaters) and `python3 -m research.product_models.team_goalie` (goalies, team win,",
           "start chance). Prior model versions are kept in the repository and named below.", "",
           "## Method (both models)", "",
           "* **Chronological walk-forward.** Games are processed in date order; every prediction uses only games before it. No season is shuffled.",
           "* **Three roles for data, declared before scoring.** *Train* 2022-23 and 2023-24 seasons (warm-up state, count dispersion);",
           "  *calibration* 2024-25 (choose the configuration by log loss, fit the calibration); *final evaluation* 2025-26, scored once and never fitted to.",
           "  (MoneyPuck labels seasons by their start year: 2022 = 2022-23.)",
           "* **Baselines on the same rows.** Each probability is scored against simple alternatives (recent empirical rate, previous live formula, league average,",
           "  home-win rate); a market counts as validated only if it beats all of them on log loss in the final season.",
           "* **Metrics.** Brier score, log loss, calibration tables by probability bin, mean absolute error for expected values, and coverage of stated ranges.",
           "* **Uncertainty slices.** Limited history (5 to 19 prior games) and changed role (ice time moved sharply) are scored separately.",
           "* **A haircut is not a calibration.** The ticket policy lowers each leg's probability by 3 points as a safety margin; that margin is a policy and is",
           "  never described as evidence of an edge.", "",
           "## What this does NOT show", "",
           "There are no historical DraftKings prices in the repository, so **profitability cannot be tested on past data and is not claimed.** The validated claim is",
           "narrower: the probabilities are better calibrated and more accurate than the alternatives on games the model had not seen. Whether prices leave an edge is",
           "evaluated *prospectively*: every ticket freezes its prices and probabilities when recorded, and results accumulate in Paper Performance and the Morning Review",
           "calibration table (a change is only suggested after 30 settled legs in a market and a 2-standard-error gap). Injuries and scratches are not modelled; players are",
           "scored conditional on playing, and the engine's \"dressed in the team's last game\" proxy decides who is priced.", "",
           f"## Skater projection — `{sk['model_version']}`", "",
           f"Chosen configuration (by calibration-season log loss): `{sk['chosen_config']}`. Count dispersion fitted on train seasons: `{sk['dispersion']}`.", "",
           "| Event | Rows | Base rate | Log loss (calibrated) | Recent-30 baseline | Previous live formula | Brier | Verdict |", "|---|---|---|---|---|---|---|---|"]
    for k, v in sv.items():
        b = v["baselines_log_loss"]
        out.append(f"| {k} | {v['rows']} | {v['base_rate']:.3f} | {v['model_log_loss']:.4f} | {b.get('recent 30-game empirical rate', float('nan')):.4f} | "
                   f"{('%.4f' % b['previous live formula']) if 'previous live formula' in b else '—'} | {v['brier']:.4f} | {v['verdict'].replace('_', ' ').lower()} |")
    mae = sk["expected_value_accuracy"]
    out += ["", "Mean absolute error of expected values, final season: " + ", ".join(f"{k} {v['mae_model']:.3f}" for k, v in mae.items()) + ".", "",
            "Live use: shots 1+ to 5+, points 1+/2+ and goals 1+ feed ticket legs (`operational/best_bets.py::compute_model_v2`, version string "
            "`player-rate-toi-v2+platt-2026-10`). Hits and blocks are displayed as expected values only (hits 1+ does not beat the recent-rate baseline). "
            "The previous live formula (`EXPERIMENTAL-rolling-l20-l60-shrunk-v1`) is kept as `compute_model` for reference; tickets recorded under it keep their model version.", "",
            f"## Goalie model — `{gv['model_version']}`", "",
            "Saves are a negative-binomial count around expected shots against (opponent shots taken blended with the team's shots allowed) times the goalie's shrunk save percentage.",
            f"Saves dispersion `{gv['alpha_saves']}`; goals-against dispersion `{gv['alpha_ga']}`. The fitted calibration made held-out log loss slightly worse, so **raw probabilities are used**.", "",
            "| Saves | Rows | Base rate | Log loss (raw) | Goalie last-10 baseline | League-average baseline | Verdict |", "|---|---|---|---|---|---|---|"]
    for k, v in sav.items():
        b = v["baselines_log_loss"]
        out.append(f"| {k} | {v['rows']} | {v['base_rate']:.3f} | {v['model_log_loss']:.4f} | {b[chr(103) + 'oalie' + chr(39) + 's last-10-start average']:.4f} | {b['league-average saves']:.4f} | {v['verdict'].replace('_', ' ').lower()} |")
    e, rc, gr = gv["expected_value_mae_final"], gv["saves_80pct_range_coverage"], gv["ga_80pct_range_coverage"]
    out += ["", f"Held-out accuracy ({e['n']} goalie games): saves MAE {e['saves_model']:.2f} (league-average guess {e['saves_league_mean']:.2f}); goals-against MAE "
            f"{e['goals_against_model']:.2f} (league {e['goals_against_league']:.2f}). Stated 80% ranges contained the result {rc['final_season']:.1%} of the time for saves and "
            f"{gr['final_season']:.1%} for goals against (conservative: goals are whole numbers).", "",
            "### Team win probability and the named-goalie question", "",
            f"Scored on {wp['games_scored']} held-out games ({wp['shootouts_excluded']} shootout games excluded: this source has no winner for them).", "",
            "| Variant | Log loss | Brier |", "|---|---|---|"]
    for k in ("home_rate_baseline", "strength_only", "strength_and_named_goalies", "strength_and_goalies_tied"):
        out.append(f"| {k.replace('_', ' ')} | {wp[k]['log_loss']:.4f} | {wp[k]['brier']:.4f} |")
    pl = gv["puck_line"]
    out += ["", "### Puck line (home −1.5 covers)", "",
            f"A margin model (least squares on the strength rating, Poisson goals with the calibration-season mean total of {pl['margin_model']['total']:.2f}) was scored on {pl['games_scored']} held-out games: "
            f"log loss {pl['model']['log_loss']:.4f} against {pl['base_rate_baseline']['log_loss']:.4f} for the base rate (lower is better). **It does not beat the base rate** "
            f"(it over-predicts home −1.5 covers: mean prediction {pl['model']['mean_pred']:.3f} against an observed {pl['model']['base_rate']:.3f}), so puck-line probabilities are not shown or priced."]
    import json as _json
    from . import moneyline_comparison as _mc, puck_line_alternative as _pa
    if _pa.OUT_PATH.exists():
        pa = _json.loads(_pa.OUT_PATH.read_text())
        out += ["", f"**Alternative, `{pa['version']}` (a direct logistic on the strength difference).** The failed result above stays on record. 2025-26 was already looked at once, so it is not used again; "
                "the alternative was judged on two earlier folds only (fit on one season, scored once on the next), then its parameters were frozen.", "",
                "| Scored season | Base rate (log loss) | Skellam (log loss) | Direct logistic (log loss) | Direct − base rate, 95% interval |", "|---|---|---|---|---|"]
        for f in pa["development"]["folds"]:
            d = f["direct_vs_base_rate_log_loss_delta"]
            out.append(f"| {f['scored_season']}-{str(f['scored_season'] + 1)[2:]} | {f['scores']['base_rate']['log_loss']:.4f} | {f['scores']['skellam']['log_loss']:.4f} | "
                       f"{f['scores']['direct_logistic']['log_loss']:.4f} | {d['point_delta']:+.4f} [{d['ci_low']:+.4f}, {d['ci_high']:+.4f}] |")
        out += ["", f"Development verdict: **{pa['development_verdict'].replace('_', ' ').lower()}**. It is not enabled: there are no puck-line prices, no settlement mapping, and the untouched evaluation set "
                "(2026-27 games, logged before they start and scored when finished) has not accumulated enough games."]
    if _mc.OUT_PATH.exists():
        mc = _json.loads(_mc.OUT_PATH.read_text())
        out += ["", "### Moneyline: strength model against the Elo that prices tickets", "",
                "Two rolling-origin folds on the same games, paired bootstrap on per-game log loss (`research/product_models/moneyline_comparison.py`, version "
                f"`{mc['version']}`). Lower log loss is better.", "",
                "| Scored season | Games | Home-rate | Elo (tickets) | Strength model | Strength − Elo, 95% interval |", "|---|---|---|---|---|---|"]
        for f in mc["folds"]:
            for key, label in (("decided_in_play_only", "decided in play"), ("all_games_incl_shootouts", "all games incl. shootouts")):
                sc, d = f[key]["scores"], f[key]["strength_vs_elo_log_loss_delta"]
                out.append(f"| {f['scored_season']}-{str(f['scored_season'] + 1)[2:]} ({label}) | {sc['elo_production']['n']} | {sc['home_rate_baseline']['log_loss']:.4f} | "
                           f"{sc['elo_production']['log_loss']:.4f} | {sc['strength_model']['log_loss']:.4f} | {d['point_delta']:+.4f} [{d['ci_low']:+.4f}, {d['ci_high']:+.4f}] |")
        out += ["", "The strength model is nominally ahead in every row but every interval reaches zero, and neither model is shown to beat a sportsbook price (no historical prices exist). "
                "Elo therefore keeps pricing tickets; `operational/moneyline_model_path.py` records both models and the market's no-vig probability on every priced candidate "
                "(the shadow scoreboard on Model Health) and offers an opt-in `NHL_ENGINE_MONEYLINE_MODEL=strength-v1` switch for the owner to use once that evidence exists."]
    st = gv["start_likelihood"]
    out += ["", "The strength-only model beats the home-rate baseline. Adding each named goalie's expected goals saved per game **did not improve** held-out forecasts "
            "(either fitted or tied to the strength coefficient), so a goalie-specific win probability is shown only as a labelled scenario, never as the model's probability.", "",
            "### Start likelihood (an estimate, not a confirmation)", "",
            f"Recent usage share and rest (back-to-back) predict who starts: log loss {st['model']['log_loss']:.4f} vs {st['share_of_last10_only']['log_loss']:.4f} (share of last 10 only) vs "
            f"{st['base_rate']['log_loss']:.4f} (base rate) on {st['samples_final']} held-out goalie-team-days. It is displayed as an estimate; saves tickets require a recorded confirmation.", "",
            "## Live-model policy", "",
            "1. A probability may supply a ticket leg only if its market appears above as *beats baselines* for that event and the player/goalie has the history the report supports "
            "(20+ prior games for skaters).",
            "2. A model that does not beat its baselines is displayed as an expected value only, or not at all; it is never relabelled as validated.",
            "3. Every model change is a new version string; reports for earlier versions stay in the repository; recorded tickets keep the version that priced them.",
            "4. Nothing retunes a model automatically. The daily review proposes, with evidence thresholds; a person decides and re-runs the validation.",
            "5. Unconfirmed starting goalies block saves tickets; the gate is not bypassed.", ""]
    return "\n".join(out)


if __name__ == "__main__":
    DOC.write_text(render())
    print(f"wrote {DOC}")
