#!/usr/bin/env python3
"""Builds an audit ZIP of the current repository for independent review.

    python3 deploy/export_audit_zip.py [--out PATH] [--tests "<summary text>"] [--release-dir DIR]

Contents: every tracked file at HEAD except SQLite databases (source, tests, dependency files, deployment
configuration, docs), plus an `audit_evidence/` folder (sanitized installed launchd jobs, the paper ledger rows,
the published ticket board, a job-health summary) and MANIFEST.json / MANIFEST.md / OMITTED_RUNTIME_DATA.md.

Never included: `.env`, credential or token files, databases, logs, the odds archive. The script reads the
values in `.env` and refuses to write the ZIP if any value of 8+ characters appears in any file it would include.
"""
from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
import plistlib
import re
import sqlite3
import subprocess
import sys
import zipfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PLIST_KEEP = ("Label", "ProgramArguments", "WorkingDirectory", "StartInterval", "StartCalendarInterval", "RunAtLoad")
DEPENDENCY_FILES = ("requirements.txt", "dashboard/requirements.txt", ".streamlit/config.toml")

OMITTED = [
    ("`.env`, `fantasy/storage/yahoo_token.enc`, `operational/auth_store.db`, any token/credential file",
     "Credentials and account data. Never exported. Key *names* in `.env`: THE_ODDS_API_KEY, NHL_ENGINE_CLOUD_PUBLISH, "
     "NHL_ENGINE_STREAMLIT_URL."),
    ("`operational/paper_bankroll.db`", "Live ledger database. Its REAL_MARKET_PAPER rows, alerts and audit log are exported "
     "as JSON in `audit_evidence/ledger_export.json`; the demo tracks are summarised only."),
    ("`operational/runtime/` (incl. `nhl.db`, model caches, state files)",
     "Runtime state, regenerated by the jobs. The published ticket board is exported as `audit_evidence/tickets_state.json`."),
    ("`operational/odds_archive/` (~1,000 raw Odds API payloads)",
     "Raw provider responses (contain provider metadata; large). The one real payload used for the PLAYER_POINTS "
     "certification is the committed fixture `tests/fixtures/draftkings_player_points_real_payload.json`."),
    ("`operational/logs/`", "Job logs; may contain request URLs. Job results are summarised in `audit_evidence/job_health.json`."),
    ("`data/raw/moneypuck/`, `research/player_sog/raw/*.csv`, other ignored research corpora",
     "Large third-party data files. The rolling-form model reads the daily MoneyPuck files; the validated shots model's "
     "corpus ends 2026-04-15."),
    ("`operational/prospective_observations.db`, `operational/special_teams_history.db`, `fantasy/storage/*.db`",
     "Other runtime/analytics databases."),
    ("Tracked `nhl.db` at the repository root", "Demo seed database (simulated data), excluded with all `*.db` files."),
]


def git(*args: str, cwd: Path = REPO) -> str:
    return subprocess.run(["git", *args], cwd=cwd, capture_output=True, text=True, check=True).stdout.strip()


def env_values() -> list[str]:
    path = REPO / ".env"
    values = []
    if path.exists():
        for line in path.read_text().splitlines():
            if "=" in line and not line.lstrip().startswith("#"):
                v = line.split("=", 1)[1].strip().strip("'\"")
                if len(v) >= 8:
                    values.append(v)
    return values


def sanitized_plists() -> dict[str, str]:
    out = {}
    agents = Path.home() / "Library" / "LaunchAgents"
    for path in sorted(agents.glob("com.nhlengine.*.plist")):
        data = plistlib.loads(path.read_bytes())
        kept = {k: data[k] for k in PLIST_KEEP if k in data}
        out[f"audit_evidence/installed_launchd/{path.name}"] = plistlib.dumps(kept).decode()
    return out


def ledger_export() -> str:
    path = REPO / "operational" / "paper_bankroll.db"
    conn = sqlite3.connect(f"file:{path}?mode=ro", uri=True)
    conn.row_factory = sqlite3.Row
    rows = [dict(r) for r in conn.execute("SELECT * FROM paper_bets WHERE track='REAL_MARKET_PAPER' ORDER BY created_at_utc")]
    for r in rows:
        r["legs"] = json.loads(r["legs_json"]) if r.get("legs_json") else None
        r["settlement"] = json.loads(r["settlement_json"]) if r.get("settlement_json") else None
    ids = [r["paper_bet_id"] for r in rows]
    marks = ",".join("?" for _ in ids) or "''"
    alerts = [dict(r) for r in conn.execute(f"SELECT * FROM ticket_alerts WHERE paper_bet_id IN ({marks})", ids)]
    audit = [dict(r) for r in conn.execute(f"SELECT * FROM paper_audit_log WHERE paper_bet_id IN ({marks}) ORDER BY id", ids)]
    other = [dict(r) for r in conn.execute(
        "SELECT track, result_status, COUNT(*) AS n FROM paper_bets WHERE track != 'REAL_MARKET_PAPER' GROUP BY 1, 2")]
    sys.path.insert(0, str(REPO))
    from operational import paper_bankroll as pb
    account = pb.account_state(conn, "REAL_MARKET_PAPER")
    conn.close()
    return json.dumps({"exported_at_utc": dt.datetime.now(dt.timezone.utc).isoformat(), "account": account,
                       "real_market_paper_tickets": rows, "ticket_alerts": alerts, "paper_audit_log": audit,
                       "other_tracks_summary": other}, indent=1, default=str)


def job_health() -> str:
    path = REPO / "operational" / "ingestion_health_cache.json"
    data = json.loads(path.read_text()) if path.exists() else {}
    keep = {k: {f: v.get(f) for f in ("last_attempt_utc", "last_status", "last_success_utc") }
            for k, v in data.items() if isinstance(v, dict)}
    detail = {k: (v.get("last_detail") or "")[:300] for k, v in data.items() if isinstance(v, dict) and v.get("last_detail")}
    return json.dumps({"components": keep, "last_detail_truncated": detail}, indent=1)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=None)
    ap.add_argument("--tests", default="(not supplied)")
    ap.add_argument("--release-dir", default=str(Path.home() / "nhl_engine_release"))
    ap.add_argument("--deployed-note", default="Streamlit Community Cloud app tracks branch master (share.streamlit.io listing)")
    args = ap.parse_args(argv)

    head = git("rev-parse", "HEAD")
    branch = git("rev-parse", "--abbrev-ref", "HEAD")
    dirty = git("status", "--porcelain", "--untracked-files=no")
    release_head = git("rev-parse", "HEAD", cwd=Path(args.release_dir)) if Path(args.release_dir).is_dir() else None
    try:
        git("fetch", "-q", "origin", "master")
        origin_master = git("rev-parse", "origin/master")
    except Exception:  # noqa: BLE001
        origin_master = None
    out = Path(args.out or Path.home() / "Downloads" / f"nhl_engine_audit_{head[:10]}.zip")

    files: dict[str, bytes] = {}
    for rel in git("ls-files", "-z").split("\0"):
        if not rel or rel.endswith((".db", ".sqlite")):
            continue
        path = REPO / rel
        if path.is_file():
            files[rel] = path.read_bytes()
    extras = {**{k: v.encode() for k, v in sanitized_plists().items()},
              "audit_evidence/ledger_export.json": ledger_export().encode(),
              "audit_evidence/job_health.json": job_health().encode(),
              "audit_evidence/test_results.txt": args.tests.encode()}
    state = REPO / "operational" / "runtime" / "tickets_state.json"
    if state.exists():
        extras["audit_evidence/tickets_state.json"] = state.read_bytes()
    files.update(extras)

    secrets = env_values()
    for rel, blob in files.items():
        text = blob.decode("utf-8", "ignore")
        for s in secrets:
            if s in text:
                print(f"REFUSING: a .env value appears in {rel}", file=sys.stderr)
                return 2
        if re.search(r"[?&]apiKey=[0-9a-fA-F]{16,}", text):
            print(f"REFUSING: an API key URL appears in {rel}", file=sys.stderr)
            return 2

    manifest = {
        "generated_at_utc": dt.datetime.now(dt.timezone.utc).isoformat(),
        "repository_head": head, "repository_branch": branch, "tracked_files_modified_at_export": bool(dirty),
        "origin_master": origin_master, "pinned_release_checkout": args.release_dir, "release_commit": release_head,
        "deployed_version": {"cloud_app": args.deployed_note, "expected_commit": origin_master,
                             "scheduled_jobs_working_directory": args.release_dir},
        "dependency_files": [f for f in DEPENDENCY_FILES if f in files],
        "python": sys.version.split()[0], "file_count": len(files),
        "tests_run_on_this_head": args.tests,
        "files_sha256": {rel: hashlib.sha256(blob).hexdigest() for rel, blob in sorted(files.items())},
    }
    md = ["# Audit export manifest", "",
          f"* Repository HEAD: `{head}` (branch `{branch}`, tracked files modified at export: {bool(dirty)})",
          f"* origin/master: `{origin_master}`",
          f"* Pinned release checkout `{args.release_dir}`: `{release_head}`",
          f"* Deployed version: {args.deployed_note}; expected commit `{origin_master}`",
          f"* Exported: {manifest['generated_at_utc']}  ·  files: {len(files)}  ·  Python {manifest['python']}",
          f"* Dependency files: {', '.join(manifest['dependency_files'])}",
          f"* Tests: {args.tests}", "",
          "Start with `docs/UNIFIED_TICKET_WORKFLOW.md`, `docs/PAPER_SETTLEMENT_RULES.md`, `docs/MARKET_COVERAGE_AUDIT.md`,",
          "`research/real_market_parlay/engine.py` (the one selector), `operational/daily_tickets.py`,",
          "`operational/paper_bankroll.py`, `operational/paper_bet_settlement_driver.py`, `operational/best_bets.py`,",
          "`tests/test_daily_tickets.py`. `audit_evidence/` holds the live ledger rows and published board.", "",
          "Labels that must stay true: probabilities are EXPERIMENTAL and uncalibrated; combined prices are ESTIMATED; "
          "prices are US-feed, not matched to DraftKings Ontario; tickets can share players/games (correlated)."]
    omitted = ["# Omitted runtime data", "", "Excluded on purpose (credentials, private account data, or regenerated runtime state):", ""]
    omitted += [f"* **{what}** — {why}" for what, why in OMITTED]
    omitted += ["", "Consequently the ZIP cannot reproduce live runs by itself. The unit tests use isolated temp databases and do not "
                "need any omitted file."]
    files["MANIFEST.json"] = json.dumps(manifest, indent=1).encode()
    files["MANIFEST.md"] = "\n".join(md).encode()
    files["OMITTED_RUNTIME_DATA.md"] = "\n".join(omitted).encode()

    out.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
        for rel, blob in sorted(files.items()):
            z.writestr(f"nhl_engine_audit/{rel}", blob)
    print(json.dumps({"zip": str(out), "bytes": out.stat().st_size, "files": len(files), "head": head,
                      "release_commit": release_head, "origin_master": origin_master}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
