#!/usr/bin/env python3
"""Builds an audit ZIP of the current repository for independent review.

    python3 deploy/export_audit_zip.py [--out PATH] [--tests "<summary text>"] [--release-dir DIR]

Contents: every tracked file at HEAD except SQLite databases (source, tests, dependency files, deployment
configuration, docs), plus an `audit_evidence/` folder (sanitized installed launchd jobs, the paper ledger rows,
the published ticket board, a job-health summary) and MANIFEST.json / MANIFEST.md / OMITTED_RUNTIME_DATA.md.

Never included: `.env`, credential or token files, databases, logs, the odds archive. The script reads the
values in `.env` and refuses to write the ZIP if any value of 8+ characters appears in any file it would include.
"""
from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
import plistlib
import re
import sqlite3
import subprocess
import sys
import zipfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PLIST_KEEP = ("Label", "ProgramArguments", "WorkingDirectory", "StartInterval", "StartCalendarInterval", "RunAtLoad")
DEPENDENCY_FILES = ("requirements.txt", "dashboard/requirements.txt", ".streamlit/config.toml")

OMITTED = [
    ("`.env`, `fantasy/storage/yahoo_token.enc`, `operational/auth_store.db`, any token/credential file",
     "Credentials and account data. Never exported. Key *names* in `.env`: THE_ODDS_API_KEY, NHL_ENGINE_CLOUD_PUBLISH, "
     "NHL_ENGINE_STREAMLIT_URL."),
    ("`operational/paper_bankroll.db`", "Live ledger database. Its REAL_MARKET_PAPER rows (both origins, with provenance), alerts, audit log, "
     "manual orders and Ontario spot checks are exported as JSON in `audit_evidence/ledger_export.json`."),
    ("`operational/runtime/` (incl. `nhl.db`, model caches, state files)",
     "Runtime state, regenerated by the jobs. The published ticket board is exported as `audit_evidence/tickets_state.json`."),
    ("`operational/odds_archive/` (~1,000 raw Odds API payloads)",
     "Raw provider responses (contain provider metadata; large). The one real payload used for the PLAYER_POINTS "
     "certification is the committed fixture `tests/fixtures/draftkings_player_points_real_payload.json`."),
    ("`operational/logs/`", "Job logs; may contain request URLs. Job results are summarised in `audit_evidence/job_health.json`."),
    ("`data/raw/moneypuck/`, `research/player_sog/raw/*.csv`, other ignored research corpora",
     "Large third-party data files. The projection models read the MoneyPuck game logs; the validation reports built from them are tracked in "
     "`docs/validation/` and summarised in `docs/MODEL_VALIDATION.md`."),
    ("`operational/prospective_observations.db`, `operational/special_teams_history.db`, `fantasy/storage/*.db`",
     "Other runtime/analytics databases."),
    ("Tracked `nhl.db` at the repository root", "Seed database, excluded with all `*.db` files. The production nhl.db contains observed NHL data only; the "
     "simulated history that once sat in it was moved to a timestamped archive by `operational/isolate_demo_history.py`."),
]


def git(*args: str, cwd: Path = REPO) -> str:
    return subprocess.run(["git", *args], cwd=cwd, capture_output=True, text=True, check=True).stdout.strip()


def env_values() -> list[str]:
    path = REPO / ".env"
    values = []
    if path.exists():
        for line in path.read_text().splitlines():
            if "=" in line and not line.lstrip().startswith("#"):
                v = line.split("=", 1)[1].strip().strip("'\"")
                if len(v) >= 8:
                    values.append(v)
    return values


def sanitized_plists() -> dict[str, str]:
    out = {}
    agents = Path.home() / "Library" / "LaunchAgents"
    for path in sorted(agents.glob("com.nhlengine.*.plist")):
        data = plistlib.loads(path.read_bytes())
        kept = {k: data[k] for k in PLIST_KEEP if k in data}
        out[f"audit_evidence/installed_launchd/{path.name}"] = plistlib.dumps(kept).decode()
    return out


def ledger_export() -> str:
    path = REPO / "operational" / "paper_bankroll.db"
    conn = sqlite3.connect(f"file:{path}?mode=ro", uri=True)
    conn.row_factory = sqlite3.Row
    rows = [dict(r) for r in conn.execute("SELECT * FROM paper_bets WHERE track='REAL_MARKET_PAPER' ORDER BY created_at_utc")]
    for r in rows:
        r["legs"] = json.loads(r["legs_json"]) if r.get("legs_json") else None
        r["settlement"] = json.loads(r["settlement_json"]) if r.get("settlement_json") else None
    ids = [r["paper_bet_id"] for r in rows]
    marks = ",".join("?" for _ in ids) or "''"
    alerts = [dict(r) for r in conn.execute(f"SELECT * FROM ticket_alerts WHERE paper_bet_id IN ({marks})", ids)]
    audit = [dict(r) for r in conn.execute(f"SELECT * FROM paper_audit_log WHERE paper_bet_id IN ({marks}) ORDER BY id", ids)]
    have = {r[0] for r in conn.execute("SELECT name FROM sqlite_master WHERE type='table'")}
    orders = [dict(r) for r in conn.execute("SELECT * FROM manual_orders ORDER BY processed_at_utc")] if "manual_orders" in have else []
    ontario = [dict(r) for r in conn.execute("SELECT * FROM ontario_verifications ORDER BY observed_at_utc")] if "ontario_verifications" in have else []
    sys.path.insert(0, str(REPO))
    from operational import paper_bankroll as pb
    account = pb.account_state(conn, "REAL_MARKET_PAPER")
    origins = pb.origin_performance(conn, "REAL_MARKET_PAPER")
    conn.close()
    return json.dumps({"exported_at_utc": dt.datetime.now(dt.timezone.utc).isoformat(), "account": account, "performance_by_origin": origins,
                       "real_market_paper_tickets": rows, "ticket_alerts": alerts, "paper_audit_log": audit,
                       "manual_orders": orders, "ontario_verifications": ontario}, indent=1, default=str)


def reconciliation() -> str:
    """Ledger vs the published ticket board: the account numbers and every ticket's status must agree."""
    sys.path.insert(0, str(REPO))
    from operational import daily_tickets, paper_bankroll as pb
    conn = pb.get_conn(REPO / "operational" / "paper_bankroll.db")
    ledger = pb.account_state(conn, "REAL_MARKET_PAPER")
    board = daily_tickets.read_state() or {}
    problems = []
    for k in ("available_cash", "open_stakes", "equity", "settled_pnl", "tickets"):
        if board.get("account", {}).get(k) != ledger[k]:
            problems.append(f"account.{k}: board {board.get('account', {}).get(k)} != ledger {ledger[k]}")
    rows = {r["paper_bet_id"]: r for r in pb.query_paper_bets(conn, track="REAL_MARKET_PAPER")}
    cards = (board.get("tickets") or []) + (board.get("manual_tickets") or []) + (board.get("earlier_open_tickets") or []) + (board.get("recent_settled") or [])
    for c in cards:
        r = rows.get(c["ticket_id"])
        if r is None:
            if c.get("recorded"):
                problems.append(f"{c['ticket_id']}: on the board as recorded but not in the ledger")
            continue
        if (r.get("origin") or "AUTOMATIC") != c.get("origin"):
            problems.append(f"{c['ticket_id']}: origin differs")
    settled = [r for r in rows.values() if r["result_status"] in ("WIN", "LOSS", "VOID")]
    pnl = round(sum(r["profit_loss"] or 0 for r in settled), 2)
    if pnl != ledger["settled_pnl"]:
        problems.append(f"sum of settled ticket P&L {pnl} != account settled_pnl {ledger['settled_pnl']}")
    conn.close()
    return json.dumps({"ledger_account": ledger, "board_account": board.get("account"), "board_generated_at_utc": board.get("generated_at_utc"),
                       "tickets_in_ledger": len(rows), "settled_in_ledger": len(settled), "problems": problems, "reconciled": not problems}, indent=1, default=str)


def postmortems() -> dict[str, bytes]:
    """Generated postmortems: one per settled losing ticket (the first loss included) and the latest daily review."""
    import tempfile
    sys.path.insert(0, str(REPO))
    import db
    from operational import daily_review, paper_bankroll as pb
    out: dict[str, bytes] = {}
    conn, nhl = pb.get_conn(REPO / "operational" / "paper_bankroll.db"), db.get_conn()
    try:
        with tempfile.TemporaryDirectory() as tmp:
            for p in daily_review.write_loss_postmortems(conn, nhl, Path(tmp)):
                out[f"audit_evidence/postmortems/{p.name}"] = p.read_bytes()
        review = daily_review.build_review(conn, nhl)
        out["audit_evidence/postmortems/latest_daily_review.json"] = json.dumps(review, indent=1, default=str).encode()
    finally:
        conn.close(); nhl.close()
    return out


def job_health() -> str:
    path = REPO / "operational" / "ingestion_health_cache.json"
    data = json.loads(path.read_text()) if path.exists() else {}
    keep = {k: {f: v.get(f) for f in ("last_attempt_utc", "last_status", "last_success_utc") }
            for k, v in data.items() if isinstance(v, dict)}
    detail = {k: (v.get("last_detail") or "")[:300] for k, v in data.items() if isinstance(v, dict) and v.get("last_detail")}
    return json.dumps({"components": keep, "last_detail_truncated": detail}, indent=1)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=None)
    ap.add_argument("--tests", default="(not supplied)")
    ap.add_argument("--release-dir", default=str(Path.home() / "nhl_engine_release"))
    ap.add_argument("--deployed-note", default="Streamlit Community Cloud app tracks branch master (share.streamlit.io listing)")
    args = ap.parse_args(argv)

    head = git("rev-parse", "HEAD")
    branch = git("rev-parse", "--abbrev-ref", "HEAD")
    dirty = git("status", "--porcelain", "--untracked-files=no")
    release_head = git("rev-parse", "HEAD", cwd=Path(args.release_dir)) if Path(args.release_dir).is_dir() else None
    try:
        git("fetch", "-q", "origin", "master")
        origin_master = git("rev-parse", "origin/master")
    except Exception:  # noqa: BLE001
        origin_master = None
    out = Path(args.out or Path.home() / "Downloads" / f"nhl_engine_audit_{head[:10]}.zip")

    files: dict[str, bytes] = {}
    for rel in git("ls-files", "-z").split("\0"):
        if not rel or rel.endswith((".db", ".sqlite")):
            continue
        path = REPO / rel
        if path.is_file():
            files[rel] = path.read_bytes()
    extras = {**{k: v.encode() for k, v in sanitized_plists().items()},
              "audit_evidence/ledger_export.json": ledger_export().encode(),
              "audit_evidence/job_health.json": job_health().encode(),
              "audit_evidence/ledger_board_reconciliation.json": reconciliation().encode(),
              **postmortems(),
              "audit_evidence/test_results.txt": args.tests.encode()}
    state = REPO / "operational" / "runtime" / "tickets_state.json"
    if state.exists():
        extras["audit_evidence/tickets_state.json"] = state.read_bytes()
    product = REPO / "operational" / "runtime" / "product_state.json"
    if product.exists():
        d = json.loads(product.read_text())
        extras["audit_evidence/product_state_summary.json"] = json.dumps({
            "generated_at_utc": d.get("generated_at_utc"), "data_through": d.get("data_through"), "et_today": d.get("et_today"),
            "games": len(d["games"]["games"]), "players": len(d["players"]), "goalies": len(d["goalies"]), "teams": len(d["teams"]),
            "model_health": d.get("model_health"), "board_sample": [g for g in d["games"]["games"] if g["date_et"] == d.get("default_date")][:12]}, indent=1).encode()
    files.update(extras)

    secrets = env_values()
    for rel, blob in files.items():
        text = blob.decode("utf-8", "ignore")
        for s in secrets:
            if s in text:
                print(f"REFUSING: a .env value appears in {rel}", file=sys.stderr)
                return 2
        if re.search(r"[?&]apiKey=[0-9a-fA-F]{16,}", text):
            print(f"REFUSING: an API key URL appears in {rel}", file=sys.stderr)
            return 2

    manifest = {
        "generated_at_utc": dt.datetime.now(dt.timezone.utc).isoformat(),
        "repository_head": head, "repository_branch": branch, "tracked_files_modified_at_export": bool(dirty),
        "origin_master": origin_master, "pinned_release_checkout": args.release_dir, "release_commit": release_head,
        "deployed_version": {"cloud_app": args.deployed_note, "expected_commit": origin_master,
                             "scheduled_jobs_working_directory": args.release_dir},
        "dependency_files": [f for f in DEPENDENCY_FILES if f in files],
        "python": sys.version.split()[0], "file_count": len(files),
        "tests_run_on_this_head": args.tests,
        "files_sha256": {rel: hashlib.sha256(blob).hexdigest() for rel, blob in sorted(files.items())},
    }
    md = ["# Audit export manifest", "",
          f"* Repository HEAD: `{head}` (branch `{branch}`, tracked files modified at export: {bool(dirty)})",
          f"* origin/master: `{origin_master}`",
          f"* Pinned release checkout `{args.release_dir}`: `{release_head}`",
          f"* Deployed version: {args.deployed_note}; expected commit `{origin_master}`",
          f"* Exported: {manifest['generated_at_utc']}  ·  files: {len(files)}  ·  Python {manifest['python']}",
          f"* Dependency files: {', '.join(manifest['dependency_files'])}",
          f"* Tests: {args.tests}", "",
          "Start with `docs/UNIFIED_TICKET_WORKFLOW.md`, `docs/PAPER_SETTLEMENT_RULES.md`, `docs/MARKET_COVERAGE_AUDIT.md`,",
          "`research/real_market_parlay/engine.py` (the one selector), `operational/daily_tickets.py`,",
          "`operational/paper_bankroll.py`, `operational/paper_bet_settlement_driver.py`, `operational/best_bets.py`, `operational/product_data.py`, `operational/manual_orders.py`, `operational/player_options.py`, `research/product_models/`,",
          "`tests/test_daily_tickets.py`. `audit_evidence/` holds the live ledger rows and published board.", "",
          "Also read `docs/MODEL_VALIDATION.md` (method, results, live-model policy), `docs/MANUAL_ORDERS.md`, `docs/ONTARIO_VERIFICATION.md`, "
          "`docs/PRODUCT_COMPLETION_CHECKLIST.md`; validation reports are in `docs/validation/`; `audit_evidence/postmortems/` holds generated postmortems "
          "(including the first losing ticket) and `audit_evidence/ledger_board_reconciliation.json` the ledger-vs-board check.", "",
          "Labels that must stay true: probabilities come from validated projection models but no profitability is claimed (no historical prices); "
          "combined parlay prices are ESTIMATED; prices are US-feed, not matched to DraftKings Ontario; tickets can share players/games (correlated); "
          "starting goalies are unconfirmed unless a person recorded a confirmation."]
    omitted = ["# Omitted runtime data", "", "Excluded on purpose (credentials, private account data, or regenerated runtime state):", ""]
    omitted += [f"* **{what}** — {why}" for what, why in OMITTED]
    omitted += ["", "Consequently the ZIP cannot reproduce live runs by itself. The unit tests use isolated temp databases and do not "
                "need any omitted file."]
    files["MANIFEST.json"] = json.dumps(manifest, indent=1).encode()
    files["MANIFEST.md"] = "\n".join(md).encode()
    files["OMITTED_RUNTIME_DATA.md"] = "\n".join(omitted).encode()

    out.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
        for rel, blob in sorted(files.items()):
            z.writestr(f"nhl_engine_audit/{rel}", blob)
    print(json.dumps({"zip": str(out), "bytes": out.stat().st_size, "files": len(files), "head": head,
                      "release_commit": release_head, "origin_master": origin_master}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
