"""
P0.8 (2026-09-24 hardening block): automated, timestamped backups for
the real, accumulating (non-reproducible) SQLite databases this project
depends on. Uses sqlite3's own online backup API (Connection.backup()),
NOT a raw file copy -- a raw copy of a live SQLite file can capture it
mid-write (especially in WAL mode) and produce a corrupt backup; the
online backup API is safe to run against a database that's actively
being written to by another process (e.g. a scheduled ingestion job).

Usage:
    python3 -m operational.backup_databases

Classification (see docs/BACKUP_AND_RESTORE.md for the full rationale):
  CRITICAL/BACKUP    -- real, accumulating, NOT fully reproducible
  REPRODUCIBLE       -- large research corpora, regenerable from source
                        (never backed up here; see docs/BACKUP_AND_RESTORE.md
                        for each one's own regeneration command)
  TEMPORARY          -- cache files, regenerated by their own job on
                        every run (never backed up)
"""
from __future__ import annotations

import datetime as dt
import shutil
import sqlite3
from pathlib import Path

from operational import ingestion_health

REPO_ROOT = Path(__file__).resolve().parent.parent
BACKUP_ROOT = REPO_ROOT / "operational" / "backups"

# CRITICAL/BACKUP: real, accumulating state with no full source-of-truth
# to regenerate it from (unlike the research corpora, which are all
# rebuildable from an external API/download). See docs/BACKUP_AND_RESTORE.md.
CRITICAL_DATABASES = {
    "nhl_db": REPO_ROOT / "nhl.db",
    "prospective_observations_db": REPO_ROOT / "operational" / "prospective_observations.db",
    "paper_bankroll_db": REPO_ROOT / "operational" / "paper_bankroll.db",
    "auth_store_db": REPO_ROOT / "operational" / "auth_store.db",
}

RETENTION_COUNT = 14  # keep the last 14 backups per database (roughly 2 weeks at a daily cadence)


def backup_one(name: str, source_path: Path, *, backup_root: Path | None = None,
                now: dt.datetime | None = None) -> dict:
    """Backs up a single SQLite database via the online backup API.
    Returns a real, structured result -- never raises past the caller
    (a backup failure must be reported, never crash the whole batch)."""
    backup_root = backup_root if backup_root is not None else BACKUP_ROOT
    now = now or dt.datetime.now(dt.timezone.utc)
    result = {"name": name, "source_path": str(source_path), "status": "SUCCESS",
              "backup_path": None, "error": None}
    if not source_path.exists():
        result["status"] = "SKIPPED"
        result["error"] = "source database does not exist yet (nothing to back up)"
        return result

    target_dir = backup_root / name
    target_dir.mkdir(parents=True, exist_ok=True)
    timestamp = now.strftime("%Y%m%dT%H%M%SZ")
    target_path = target_dir / f"{name}_{timestamp}.db"

    try:
        source_conn = sqlite3.connect(str(source_path))
        dest_conn = sqlite3.connect(str(target_path))
        with dest_conn:
            source_conn.backup(dest_conn)
        source_conn.close()
        dest_conn.close()
        result["backup_path"] = str(target_path)
    except Exception as exc:  # noqa: BLE001 -- one DB's failure must not abort the batch
        result["status"] = "FAILED"
        result["error"] = f"{exc.__class__.__name__}: {exc}"
        if target_path.exists():
            target_path.unlink()  # never leave a partial/corrupt backup file behind
        return result

    _apply_retention(target_dir, name)
    return result


def _apply_retention(target_dir: Path, name: str, *, keep: int = RETENTION_COUNT) -> None:
    backups = sorted(target_dir.glob(f"{name}_*.db"))
    for stale in backups[:-keep] if len(backups) > keep else []:
        stale.unlink()


def run_all_backups(*, backup_root: Path | None = None, now: dt.datetime | None = None) -> dict:
    results = {name: backup_one(name, path, backup_root=backup_root, now=now)
               for name, path in CRITICAL_DATABASES.items()}
    failures = [r for r in results.values() if r["status"] == "FAILED"]
    overall_status = "FAILED" if failures else "SUCCESS"
    summary = {"status": overall_status, "results": results, "failure_count": len(failures)}
    ingestion_health.record_run("database_backups", summary)
    return summary


def restore_from_backup(backup_path: Path, restore_to: Path) -> None:
    """Restores a backup file to `restore_to` (a NEW path -- this never
    overwrites the live database automatically; that's a deliberate,
    separate, explicit action per docs/BACKUP_AND_RESTORE.md's own
    restore procedure). Uses a plain file copy: a backup file produced
    by backup_one() is already a complete, consistent, closed SQLite
    file (the online backup API only returns after the copy is fully
    consistent), so a plain copy of IT (as opposed to a live database)
    is safe."""
    restore_to.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(backup_path, restore_to)


def main() -> None:
    import json
    from operational import deployment_mode as dm
    if not dm.require_active_scheduler_or_exit("backup_databases"):
        return
    summary = run_all_backups()
    print(json.dumps(summary, indent=2, sort_keys=True, default=str))


if __name__ == "__main__":
    main()
