"""
Write protection for personal logs, as simple as it can be and still hold in a PUBLIC repository.

The problem: orders travel through a public GitHub queue and the published data is public, so nothing secret can be put in an order and a log's
code (which is published, hashed) cannot also be the thing that authorises writes. The fix is a signature, not a password in transit:

  * the log has a WRITE KEY, generated by the app when the log is created and shown once (100 bits; the code stays a memorable name);
  * the app derives an Ed25519 key pair from the write key (scrypt, salted by the log) and puts only the PUBLIC key in the creation order;
  * every later order is signed with the private key, which exists only in the creator's browser session;
  * the engine verifies the signature against the stored public key and refuses anything else (`BAD_SIGNATURE`).

Anyone can read the queue and the public key; none of it lets them write. A replayed order does nothing (every order id is answered once). Reading a
log is NOT protected: the data is public by construction. A lost write key cannot be recovered; the log stays readable and a new log can be made.
"""
from __future__ import annotations

import hashlib
import json
import re
import secrets

from operational import ed25519_pure

ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"        # no 0/O/1/I
SALT = b"nhl-engine/personal-log/write-v1|"
SALT_PASSCODE = b"nhl-engine/personal-account/passcode-v2|"
KEY_GROUPS, GROUP_LEN = 5, 4
PASSCODE_LEN = 8                                     # 8 characters of a 32-letter alphabet = 40 bits, written XXXX-XXXX


def new_passcode() -> str:
    """The everyday write secret of a personal account: 8 characters from a 32-letter alphabet (40 bits), grouped XXXX-XXXX. Short enough to type from a phone; the key pair derived from it
    uses a much slower derivation than the long key (see _seed), because the public half is published and an attacker may try passcodes offline."""
    chars = "".join(secrets.choice(ALPHABET) for _ in range(PASSCODE_LEN))
    return f"{chars[:4]}-{chars[4:]}"


def new_write_key() -> str:
    """20 characters from a 32-letter alphabet = 100 bits, grouped for reading: ABCD-EFGH-JKLM-NPQR-STUV."""
    chars = [secrets.choice(ALPHABET) for _ in range(KEY_GROUPS * GROUP_LEN)]
    return "-".join("".join(chars[i:i + GROUP_LEN]) for i in range(0, len(chars), GROUP_LEN))


def normalize_key(key) -> str:
    return re.sub(r"[^A-Z0-9]", "", str(key or "").upper())


def valid_key_shape(key) -> bool:
    """A 20-character write key (earlier logs and the owner's claim phrase) or an 8-character account passcode."""
    k = normalize_key(key)
    return len(k) in (KEY_GROUPS * GROUP_LEN, PASSCODE_LEN) and all(c in ALPHABET for c in k)


def is_passcode(key) -> bool:
    return len(normalize_key(key)) == PASSCODE_LEN


def _seed(write_key: str, log_hash: str) -> bytes:
    k = normalize_key(write_key)
    if len(k) == PASSCODE_LEN:
        # 40 bits is too few to resist a determined offline search at ordinary speed, so each guess costs about 0.15-0.3 s and 32 MiB (n=2^15): about 10^3 CPU-years to try them all.
        return hashlib.scrypt(k.encode(), salt=SALT_PASSCODE + log_hash.encode(), n=2 ** 15, r=8, p=1, dklen=32, maxmem=96 * 1024 * 1024)
    return hashlib.scrypt(k.encode(), salt=SALT + log_hash.encode(), n=2 ** 14, r=8, p=1, dklen=32)


def public_key_hex(write_key: str, log_hash: str) -> str:
    return ed25519_pure.public_key(_seed(write_key, log_hash)).hex()


def canonical(order: dict) -> bytes:
    return json.dumps({k: v for k, v in order.items() if k != "sig"}, sort_keys=True, separators=(",", ":"), default=str).encode()


def sign(order: dict, write_key: str, log_hash: str) -> dict:
    """Returns a copy of the order with its signature. Needs the write key; never stored."""
    out = dict(order)
    out.pop("sig", None)
    out["sig"] = ed25519_pure.sign(_seed(write_key, log_hash), canonical(out)).hex()
    return out


def verify(order: dict, public_hex: str | None) -> bool:
    """True only when the order's signature is valid for this public key."""
    try:
        if not public_hex or not re.fullmatch(r"[0-9a-f]{64}", public_hex) or not re.fullmatch(r"[0-9a-f]{128}", str(order.get("sig", ""))):
            return False
        return ed25519_pure.verify(bytes.fromhex(public_hex), canonical(order), bytes.fromhex(order["sig"]))
    except Exception:  # noqa: BLE001 - any failure to verify is a refusal
        return False
